"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Provincia = void 0;
var Provincia;
(function (Provincia) {
    Provincia["A_Corunya"] = "A Coru\u00F1a";
    Provincia["Alava"] = "\u00C1lava";
    Provincia["Albacete"] = "Albacete";
    Provincia["Alicante"] = "Alicante";
    Provincia["Almeria"] = "Almer\u00EDa";
    Provincia["Asturias"] = "Asturias";
    Provincia["Avila"] = "\u00C1vila";
    Provincia["Badajoz"] = "Badajoz";
    Provincia["Baleares"] = "Baleares";
    Provincia["Barcelona"] = "Barcelona";
    Provincia["Burgos"] = "Burgos";
    Provincia["Caceres"] = "C\u00E1ceres";
    Provincia["Cadiz"] = "C\u00E1diz";
    Provincia["Cantabria"] = "Cantabria";
    Provincia["Castellon"] = "Castell\u00F3n";
    Provincia["Ciudad_Real"] = "Ciudad Real";
    Provincia["Cordoba"] = "C\u00F3rdoba";
    Provincia["Cuenca"] = "Cuenca";
    Provincia["Girona"] = "Girona";
    Provincia["Granada"] = "Granada";
    Provincia["Guadalajara"] = "Guadalajara";
    Provincia["Gipuzkoa"] = "Gipuzkoa";
    Provincia["Huelva"] = "Huelva";
    Provincia["Huesca"] = "Huesca";
    Provincia["Jaen"] = "Ja\u00E9n";
    Provincia["La_Rioja"] = "La Rioja";
    Provincia["Las_Palmas"] = "Las Palmas";
    Provincia["Leon"] = "Le\u00F3n";
    Provincia["Lerida"] = "L\u00E9rida";
    Provincia["Lugo"] = "Lugo";
    Provincia["Madrid"] = "Madrid";
    Provincia["Malaga"] = "M\u00E1laga";
    Provincia["Murcia"] = "Murcia";
    Provincia["Navarra"] = "Navarra";
    Provincia["Ourense"] = "Ourense";
    Provincia["Palencia"] = "Palencia";
    Provincia["Pontevedra"] = "Pontevedra";
    Provincia["Salamanca"] = "Salamanca";
    Provincia["Segovia"] = "Segovia";
    Provincia["Sevilla"] = "Sevilla";
    Provincia["Soria"] = "Soria";
    Provincia["Tarragona"] = "Tarragona";
    Provincia["Santa_Cruz_de_Tenerife"] = "Santa Cruz de Tenerife";
    Provincia["Teruel"] = "Teruel";
    Provincia["Toledo"] = "Toledo";
    Provincia["Valencia"] = "Valencia";
    Provincia["Valladolid"] = "Valladolid";
    Provincia["Vizcaya"] = "Vizcaya";
    Provincia["Zamora"] = "Zamora";
    Provincia["Zaragoza"] = "Zaragoza";
    Provincia["Ceuta"] = "Ceuta";
    Provincia["Melilla"] = "Melilla";
})(Provincia = exports.Provincia || (exports.Provincia = {}));
